version: '3.7'
services:
  family-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - postgres
    env_file:
      - .env

  family-api-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    depends_on:
      - family-api
      - postgres
    entrypoint: /app/run-migration.sh
    env_file:
      - .env

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
